language: objective-c
osx_image: xcode8.1
script:
- xctool -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Static Library (C++98)" build test
- xctool -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Static Library (C++11)" build test
before_install:
- rvm get stable
- rvm reload
- bash Scripts/travis-before.sh
after_success:
- bash Scripts/travis-after.sh
