language: objective-c
cache:
    directories:
    - $HOME/.ccache
install:
- gem install xcpretty
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
- brew install macmade/tap/xcode-coveralls
script:
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Static Library" build analyze test | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Dynamic Library" build analyze test | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Framework" build analyze test | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ iOS Static Library" -destination generic/platform=iOS build analyze | xcpretty
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
after_success:
- bash Scripts/travis-after.sh
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
