name: ci-win
on:   [push]
jobs:
    ci:
        runs-on: windows-latest
        strategy:
            matrix:
                run-config:
                    - { platform: 'x64', toolset: 'x64', configuration: 'Debug',   solution: 'CoreFoundation++.sln' }
                    - { platform: 'x64', toolset: 'x64', configuration: 'Release', solution: 'CoreFoundation++.sln' }
                    - { platform: 'x86', toolset: 'x64', configuration: 'Debug',   solution: 'CoreFoundation++.sln' }
                    - { platform: 'x86', toolset: 'x64', configuration: 'Release', solution: 'CoreFoundation++.sln' }
        steps:
            
            - uses: actions/checkout@v1
              with:
                submodules: 'recursive'
                
            - uses: macmade/action-msbuild@v1.0.0
            
            - uses: act10ns/slack@v1
              if:   ${{ always() }}
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                status:     ${{ job.status }}
                steps:      ${{ toJson(steps) }}
                channel:    '#ci'
